[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
